version: 2
jobs:
  build:
    docker:
      - image: node:latest
    steps:
      - run:
          name: Versions
          command: npm version
      - checkout
      - run: git reset --hard HEAD
      - run: git checkout -b national-holidays-jp;
      - run: curl -s https://holidays-jp.github.io/api/v1/date.json > national_holidays_jp.json
      - run: git config user.email "harada.tsubasa.0422@gmail.com"
      - run: git config user.name "hrdtbs"
      - run: git add national_holidays_jp.json
      - run: git commit -m 'feat(*):update national_holidays_jp.json'
      - run: git push -f origin national-holidays-jp
workflows:
  version: 2
  normal_test_workflow:
    jobs:
      - build
  nightly_workflow:
    triggers:
      - schedule:
      # http://pubs.opengroup.org/onlinepubs/7908799/xcu/crontab.html
          cron: "* * 31 * *" 
          filters:
            branches:
              only:
                - master
    jobs:
      - build